### ISSUE TITLE
Error anytime i try wal-steam in cmd

### ISSUE THREAD

**Issue by trentonjeffro** [kotajacob/wal_steam#52]
Traceback (most recent call last):
  File "C:\Users\trent\AppData\Local\Programs\Python\Python35\Scripts\wal-steam-script.py", line 9, in <module>
    load_entry_point('wal-steam==1.2.0', 'console_scripts', 'wal-steam')()
  File "C:\Users\trent\AppData\Local\Programs\Python\Python35\Scripts\wal_steam.py", line 435, in main
    checkInstall(oSys)
  File "C:\Users\trent\AppData\Local\Programs\Python\Python35\Scripts\wal_steam.py", line 345, in checkInstall
    checkSkin(oSys)
  File "C:\Users\trent\AppData\Local\Programs\Python\Python35\Scripts\wal_steam.py", line 251, in checkSkin
    copy_tree(METRO_PATCH_COPY, os.path.join(steam_dir, SKIN_NAME))
  File "c:\users\trent\appdata\local\programs\python\python35\lib\distutils\dir_util.py", line 124, in copy_tree
    "cannot copy tree '%s': not a directory" % src)
distutils.errors.DistutilsFileError: cannot copy tree 'C:\Users\trent\.cache\wal_steam\metroPatchZip\UPMetroSkin-196feafc14deae103355b4fee1ecc4cda9288c7f/Unofficial 4.2.4 Patch/Main Files [Install First]': not a directory

**Comment by kotajacob** [comment]
I'll look into it, what version of windows are you running? and what version of python? `python --version` to check.

**Comment by kotajacob** [comment]
I pushed out a new release that should fix this problem (although I was unable to have the error occur in my tests in the first place so if it's still not working let me know) `pip install wal-steam -U` to update if you installed with pip
